### ISSUE TITLE
installing with composer and SF2

### ISSUE THREAD

**Issue by gpapin** [Rebolon/PagerBundle#2]
Hi,
I've got an issue when installing your bundle since your commit number 5425ccc94f4daef8617e821699ac635d6f84b47a

> php app/console cache:clear
> 
> Fatal error: Class 'Rebolon\PagerBundle\RebolonPagerBundle' not found in >/Users/gpapin/Sites/Mediatek/app/AppKernel.php on line 29

I use Symfony 2.1

**Comment by Rebolon** [comment]
Woups sorry i missed your issue, i'll have a look to that. Did you test with last version ?

**Comment by gpapin** [comment]
Hi, i'm a bit late too.
the problem still with the latest version, i now use SF 2.3

**Comment by Rebolon** [comment]
okay, i'll test it with SF2.3

**Comment by Rebolon** [comment]
In your AppKernel.php change that line : 
   new Rebolon\PagerBundle\RebolonPagerBundle(),

by this one : 
   new Rebolon\Bundle\Pager\RebolonPagerBundle(),

The problem is in the explanation of how to register the bundle into Symfony.
Maybe i should also change the namespace as Sf does : Rebolon\Bundle\PagerBundle\PagerBundle(),
But it doesn't seems to be necessary.
